const CKEY="ld_ultimate_cloud_cfg";
let cfg=JSON.parse(localStorage.getItem(CKEY)||"null"),sb=null,user=null,profile=null,page="dashboard";
const $=x=>document.getElementById(x),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),money=n=>"₹"+Number(n||0).toLocaleString("en-IN"),today=()=>new Date().toISOString().slice(0,10);
const classes=["Nursery","LKG","UKG","1","2","3","4","5","6","7","8","9","10"];
const navItems=[
["dashboard","⌂","Dashboard"],["admissions","＋","Admissions"],["students","◉","Students"],["attendance","✓","Attendance"],["fees","₹","Fees"],["staff","♟","Staff"],["exams","▣","Exams & Marks"],["timetable","▦","Timetable"],["homework","✎","Homework"],["transport","↔","Transport"],["library","▤","Library"],["income","↗","Income"],["expenses","↘","Expenses"],["balance","⚖","Balance Sheet"],["notices","◫","Notices"],["certificates","◇","Certificates"],["documents","□","Documents"],["users","♙","Users & Roles"],["reports","▥","Reports"],["settings","⚙","Settings"]];
const perms={
 super_admin:["*"],admin:["dashboard","admissions","students","attendance","fees","staff","exams","timetable","homework","transport","library","income","expenses","balance","notices","certificates","documents","users","reports","settings"],
 principal:["dashboard","admissions","students","attendance","fees","staff","exams","timetable","homework","transport","library","income","expenses","balance","notices","certificates","documents","reports","settings"],
 admission:["dashboard","admissions","students","documents","certificates","reports"],
 accountant:["dashboard","students","fees","income","expenses","balance","reports"],
 teacher:["dashboard","students","attendance","exams","timetable","homework","notices","reports"],
 librarian:["dashboard","students","library","reports"],
 transport:["dashboard","students","transport","reports"],
 student:["dashboard","students","attendance","fees","exams","timetable","homework","notices","documents"],
 parent:["dashboard","students","attendance","fees","exams","timetable","homework","notices","documents"],
 viewer:["dashboard","notices"]
};
const can=k=>profile&&(profile.role==="super_admin"||perms[profile.role]?.includes("*")||perms[profile.role]?.includes(k));
const crudRoles={
 admissions:["super_admin","admin","principal","admission"],students:["super_admin","admin","principal","admission"],attendance:["super_admin","admin","principal","teacher"],
 fees:["super_admin","admin","principal","accountant"],staff:["super_admin","admin","principal"],exams:["super_admin","admin","principal","teacher"],timetable:["super_admin","admin","principal","teacher"],
 homework:["super_admin","admin","principal","teacher"],transport:["super_admin","admin","principal","transport"],library:["super_admin","admin","principal","librarian"],
 income:["super_admin","admin","principal","accountant"],expenses:["super_admin","admin","principal","accountant"],notices:["super_admin","admin","principal","teacher"],
 certificates:["super_admin","admin","principal","admission"],documents:["super_admin","admin","principal","admission"]
};
const canEdit=k=>crudRoles[k]?.includes(profile?.role);

const F=(name,label,type="text",req=false,cls="")=>[name,label,type,req,cls];
const modules={
admissions:{title:"Admissions",table:"admissions",fields:[
["#","Student Identity"],F("admission_no","Admission No.","text",true),F("admission_date","Admission Date","date",true),F("academic_session","Academic Session","text",true),F("student_name","Student Full Name","text",true),F("class_name","Admission Class","class",true),F("section","Section"),F("roll_no","Roll No."),F("dob","Date of Birth","date",true),F("gender","Gender","gender",true),F("blood_group","Blood Group","blood"),F("aadhaar_last4","Aadhaar Last 4 Digits"),F("pen_no","PEN / Student ID"),F("apaar_id","APAAR ID"),F("udise_student_id","UDISE Student ID"),
["#","Parent / Guardian"],F("father_name","Father Name","text",true),F("father_occupation","Father Occupation"),F("mother_name","Mother Name"),F("mother_occupation","Mother Occupation"),F("guardian_name","Guardian Name"),F("relation","Guardian Relation"),F("primary_phone","Primary Mobile","text",true),F("alternate_phone","Alternate Mobile"),F("email","Email","email"),F("parent_email","Parent Login Email","email"),
["#","Social & Address"],F("category","Category","category"),F("religion","Religion"),F("nationality","Nationality"),F("mother_tongue","Mother Tongue"),F("minority","Minority","yesno"),F("bpl","BPL/EWS","yesno"),F("disability","CWSN/Disability","yesno"),F("disability_type","Disability Type"),F("address","Current Address","textarea",false,"full"),F("permanent_address","Permanent Address","textarea",false,"full"),F("village","Village/Town"),F("post","Post"),F("police_station","Police Station"),F("district","District"),F("state","State"),F("pincode","PIN Code"),
["#","Previous School & Services"],F("previous_school","Previous School"),F("previous_class","Previous Class"),F("last_result","Last Result"),F("tc_no","TC No."),F("tc_date","TC Date","date"),F("transport_required","Transport Required","yesno"),F("route_name","Transport Route"),F("hostel_required","Hostel Required","yesno"),F("medical_note","Medical / Allergy Note","textarea",false,"full"),F("emergency_contact","Emergency Contact"),F("admission_status","Admission Status","admissionstatus",true)
],cols:[["admission_no","Adm No"],["student_name","Student"],["class_name","Class"],["father_name","Father"],["primary_phone","Mobile"],["academic_session","Session"],["admission_status","Status"]]},
students:{title:"Students",table:"students",fields:[F("student_name","Student Name","text",true),F("roll_no","Roll No."),F("class_name","Class","class",true),F("section","Section"),F("admission_no","Admission No."),F("dob","DOB","date"),F("gender","Gender","gender"),F("father_name","Father Name"),F("mother_name","Mother Name"),F("phone","Phone"),F("student_email","Student Login Email","email"),F("parent_email","Parent Login Email","email"),F("pen_no","PEN No."),F("apaar_id","APAAR ID"),F("udise_student_id","UDISE Student ID"),F("address","Address","textarea",false,"full"),F("status","Status","studentstatus",true)],cols:[["roll_no","Roll"],["student_name","Student"],["class_name","Class"],["section","Sec"],["admission_no","Adm No"],["phone","Mobile"],["status","Status"]]},
attendance:{title:"Attendance",table:"attendance",fields:[F("date","Date","date",true),F("student_name","Student Name","text",true),F("class_name","Class","class",true),F("roll_no","Roll No."),F("status","Status","attendance",true),F("remark","Remark")],cols:[["date","Date"],["student_name","Student"],["class_name","Class"],["roll_no","Roll"],["status","Status"],["remark","Remark"]]},
fees:{title:"Fees",table:"fees",fields:[F("date","Date","date",true),F("receipt_no","Receipt No."),F("student_name","Student Name","text",true),F("class_name","Class","class",true),F("fee_type","Fee Type","feetype",true),F("total_fee","Total Fee","number",true),F("discount","Discount","number"),F("paid_amount","Paid Amount","number",true),F("payment_mode","Payment Mode","payment"),F("transaction_id","Transaction ID"),F("due_date","Due Date","date"),F("note","Note","textarea",false,"full")],cols:[["date","Date"],["receipt_no","Receipt"],["student_name","Student"],["class_name","Class"],["fee_type","Type"],["total_fee","Total"],["paid_amount","Paid"],["due_amount","Due"]]},
staff:{title:"Staff",table:"staff",fields:[F("employee_id","Employee ID"),F("staff_name","Full Name","text",true),F("role_name","Designation","text",true),F("subject","Subject"),F("qualification","Qualification"),F("phone","Phone"),F("email","Email","email"),F("aadhaar_last4","Aadhaar Last 4"),F("joining_date","Joining Date","date"),F("salary","Monthly Salary","number"),F("bank_name","Bank Name"),F("account_last4","Account Last 4"),F("ifsc","IFSC"),F("address","Address","textarea",false,"full"),F("status","Status","staffstatus")],cols:[["employee_id","ID"],["staff_name","Name"],["role_name","Designation"],["subject","Subject"],["phone","Phone"],["salary","Salary"],["status","Status"]]},
exams:{title:"Exams & Marks",table:"exams",fields:[F("exam_name","Exam Name","text",true),F("exam_date","Exam Date","date"),F("student_name","Student Name","text",true),F("class_name","Class","class",true),F("roll_no","Roll No."),F("subject","Subject","text",true),F("max_marks","Max Marks","number",true),F("marks_obtained","Marks Obtained","number",true),F("grade","Grade"),F("remark","Remark")],cols:[["exam_name","Exam"],["student_name","Student"],["class_name","Class"],["subject","Subject"],["max_marks","Max"],["marks_obtained","Marks"],["percentage","%"],["grade","Grade"]]},
timetable:{title:"Timetable",table:"timetable",fields:[F("class_name","Class","class",true),F("section","Section"),F("day_name","Day","day",true),F("period_no","Period No.","number",true),F("start_time","Start Time","time"),F("end_time","End Time","time"),F("subject","Subject","text",true),F("teacher_name","Teacher Name")],cols:[["class_name","Class"],["section","Sec"],["day_name","Day"],["period_no","Period"],["start_time","Start"],["end_time","End"],["subject","Subject"],["teacher_name","Teacher"]]},
homework:{title:"Homework",table:"homework",fields:[F("date","Date","date",true),F("class_name","Class","class",true),F("section","Section"),F("subject","Subject","text",true),F("title","Title","text",true),F("description","Homework","textarea",true,"full"),F("due_date","Due Date","date"),F("teacher_name","Teacher")],cols:[["date","Date"],["class_name","Class"],["subject","Subject"],["title","Title"],["due_date","Due"],["teacher_name","Teacher"]]},
transport:{title:"Transport",table:"transport",fields:[F("route_name","Route Name","text",true),F("vehicle_no","Vehicle No."),F("driver_name","Driver Name"),F("driver_phone","Driver Phone"),F("student_name","Student Name"),F("class_name","Class","class"),F("pickup_point","Pickup Point"),F("monthly_fee","Monthly Fee","number"),F("status","Status","studentstatus")],cols:[["route_name","Route"],["vehicle_no","Vehicle"],["student_name","Student"],["class_name","Class"],["pickup_point","Pickup"],["driver_name","Driver"],["monthly_fee","Fee"]]},
library:{title:"Library",table:"library",fields:[F("book_code","Book Code","text",true),F("book_title","Book Title","text",true),F("author","Author"),F("category","Category"),F("student_name","Issued To"),F("issue_date","Issue Date","date"),F("due_date","Due Date","date"),F("return_date","Return Date","date"),F("status","Status","bookstatus")],cols:[["book_code","Code"],["book_title","Book"],["author","Author"],["student_name","Issued To"],["issue_date","Issue"],["due_date","Due"],["status","Status"]]},
income:{title:"Income",table:"income",fields:[F("date","Date","date",true),F("source","Source","text",true),F("amount","Amount","number",true),F("payment_mode","Payment Mode","payment"),F("reference_no","Reference No."),F("note","Note","textarea",false,"full")],cols:[["date","Date"],["source","Source"],["amount","Amount"],["payment_mode","Mode"],["reference_no","Reference"]]},
expenses:{title:"Expenses",table:"expenses",fields:[F("date","Date","date",true),F("category","Category","text",true),F("vendor","Vendor/Payee"),F("amount","Amount","number",true),F("payment_mode","Payment Mode","payment"),F("reference_no","Reference No."),F("note","Note","textarea",false,"full")],cols:[["date","Date"],["category","Category"],["vendor","Vendor"],["amount","Amount"],["payment_mode","Mode"],["reference_no","Reference"]]},
notices:{title:"Notices",table:"notices",fields:[F("date","Date","date",true),F("title","Notice Title","text",true),F("audience","Audience","audience",true),F("message","Message","textarea",true,"full")],cols:[["date","Date"],["title","Title"],["audience","Audience"],["message","Message"]]},
certificates:{title:"Certificates",table:"certificates",fields:[F("date","Date","date",true),F("certificate_type","Certificate Type","certtype",true),F("student_name","Student Name","text",true),F("class_name","Class","class"),F("certificate_no","Certificate No."),F("purpose","Purpose"),F("remark","Remark")],cols:[["date","Date"],["certificate_type","Type"],["student_name","Student"],["class_name","Class"],["certificate_no","No."],["purpose","Purpose"]]},
documents:{title:"Documents",table:"documents",fields:[F("student_name","Student Name","text",true),F("class_name","Class","class"),F("document_type","Document Type","doctype",true),F("document_no","Document No."),F("verified","Verified","yesno"),F("remark","Remark")],cols:[["student_name","Student"],["class_name","Class"],["document_type","Document"],["document_no","No."],["verified","Verified"],["remark","Remark"]]}
};

function show(id){["setup","login","signup","app"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function toast(m){$("toast").textContent=m;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2500)}
function init(){sb=window.supabase.createClient(cfg.url,cfg.key)}
async function boot(){if(!cfg)return show("setup");try{init();let {data:{session}}=await sb.auth.getSession();if(!session)return show("login");user=session.user;await loadProfile();show("app");bind();buildNav();render("dashboard")}catch(e){show("setup")}}
async function loadProfile(){let {data}=await sb.from("profiles").select("*").eq("id",user.id).single();profile=data}
$("setupForm").onsubmit=e=>{e.preventDefault();cfg={url:$("url").value.trim(),key:$("key").value.trim()};localStorage.setItem(CKEY,JSON.stringify(cfg));location.reload()}
$("changeCloud").onclick=()=>{localStorage.removeItem(CKEY);location.reload()};$("signupShow").onclick=()=>show("signup");$("back").onclick=()=>show("login");
$("signupForm").onsubmit=async e=>{e.preventDefault();let {error}=await sb.auth.signUp({email:$("semail").value.trim(),password:$("spass").value,options:{data:{full_name:$("sname").value.trim()}}});if(error)return toast(error.message);toast("Account created. Email confirmation may be required.");show("login")}
$("loginForm").onsubmit=async e=>{e.preventDefault();let {data,error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)return toast(error.message);user=data.user;await loadProfile();show("app");bind();buildNav();render("dashboard")}
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()};$("menu").onclick=()=>$("side").classList.toggle("open");$("close").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};
let bound=false;function bind(){if(bound)return;bound=true;$("addTop").onclick=()=>openAdd(page)}
function buildNav(){$("roleBadge").textContent=(profile?.role||"viewer").replaceAll("_"," ").toUpperCase();$("nav").innerHTML=navItems.filter(x=>can(x[0])).map(x=>`<button data-p="${x[0]}">${x[1]} <span>${x[2]}</span></button>`).join("");document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{render(b.dataset.p);$("side").classList.remove("open")})}
function setHead(t,s,add){$("title").textContent=t;$("subtitle").textContent=s||"";$("addTop").style.display=add?"inline-block":"none";document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.p===page))}
async function cnt(t){let {count}=await sb.from(t).select("*",{count:"exact",head:true});return count||0}
async function sum(t,c){let {data}=await sb.from(t).select(c);return (data||[]).reduce((a,x)=>a+Number(x[c]||0),0)}
function stat(l,v,h){return `<div class="stat"><div class="label">${l}</div><div class="value">${v}</div><div class="hint">${h}</div></div>`}
async function dashboard(){setHead("Dashboard",`Welcome, ${profile?.full_name||user.email} • ${profile?.role||""}`,false);let [s,st,a,f,i,e]=await Promise.all([cnt("students"),cnt("staff"),cnt("admissions"),sum("fees","paid_amount"),sum("income","amount"),sum("expenses","amount")]);$("content").innerHTML=`<div class="cards">${stat("Students",s,"Current records")}${stat("Staff",st,"School staff")}${stat("Admissions",a,"Admission records")}${stat("Net Balance",money(f+i-e),"Fees + income - expense")}</div><div class="grid2"><div class="panel"><div class="panel-head"><h3>Quick Actions</h3></div><div class="quick">${canEdit("admissions")?`<button class="primary" onclick="render('admissions');setTimeout(()=>openAdd('admissions'),80)">+ New Admission</button>`:""}${canEdit("fees")?`<button class="secondary" onclick="render('fees');setTimeout(()=>openAdd('fees'),80)">+ Collect Fee</button>`:""}${canEdit("attendance")?`<button class="secondary" onclick="render('attendance');setTimeout(()=>openAdd('attendance'),80)">+ Attendance</button>`:""}</div></div><div class="panel"><h3>Permission</h3><p><span class="badge green">${esc(profile?.role||"viewer")}</span></p><p class="muted">आपको केवल आपके role के अनुसार modules और actions दिखेंगे।</p></div></div>`}
function opt(type,val=""){let map={class:classes,gender:["Male","Female","Other"],blood:["A+","A-","B+","B-","AB+","AB-","O+","O-","Unknown"],category:["General","OBC","SC","ST","EWS","Other"],yesno:["No","Yes"],attendance:["Present","Absent","Leave"],payment:["Cash","UPI","Bank Transfer","Card","Cheque","Other"],feetype:["Admission","Tuition","Annual","Exam","Transport","Computer","Smart Class","Other"],admissionstatus:["Enquiry","Applied","Admitted","Waitlisted","Cancelled"],studentstatus:["Active","Inactive","Transferred","Passed Out"],staffstatus:["Active","On Leave","Inactive"],day:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],bookstatus:["Available","Issued","Returned","Lost"],audience:["All","Students","Parents","Teachers","Staff"],certtype:["Bonafide","Character","Transfer Certificate","Fee Certificate","Study Certificate","Other"],doctype:["Birth Certificate","Aadhaar","Photo","Previous Marksheet","Transfer Certificate","Caste Certificate","Income Certificate","Residence Certificate","Disability Certificate","APAAR/PEN Proof","Other"]};return (map[type]||[]).map(x=>`<option ${x==val?"selected":""}>${x}</option>`).join("")}
function fieldHTML(f,row={}){if(f[0]==="#")return `<div class="section-title">${f[1]}</div>`;let [n,l,t="text",r=false,cls=""]=f,v=row[n]??"",required=r?"required":"",cl=cls||"";if(["class","gender","blood","category","yesno","attendance","payment","feetype","admissionstatus","studentstatus","staffstatus","day","bookstatus","audience","certtype","doctype"].includes(t))return `<div class="field ${cl}"><label>${l}</label><select name="${n}" ${required}><option value="">Select</option>${opt(t,v)}</select></div>`;if(t==="textarea")return `<div class="field ${cl||"full"}"><label>${l}</label><textarea name="${n}" ${required}>${esc(v)}</textarea></div>`;return `<div class="field ${cl}"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" ${required}></div>`}
async function list(k,term=""){page=k;let m=modules[k];setHead(m.title,"Cloud synced records",canEdit(k));let q=sb.from(m.table).select("*").order("created_at",{ascending:false});let {data,error}=await q;if(error){$("content").innerHTML=`<div class="panel">${esc(error.message)}</div>`;return}let rows=data||[];if(term){let t=term.toLowerCase();rows=rows.filter(r=>Object.values(r).some(v=>String(v??"").toLowerCase().includes(t)))}$("content").innerHTML=`<div class="panel"><div class="panel-head"><h3>${m.title}</h3><div class="toolbar"><input id="search" class="search" placeholder="Search...">${canEdit(k)?`<button class="primary" onclick="openAdd('${k}')">+ Add New</button>`:""}</div></div>${table(k,rows)}</div>`;$("search").value=term;$("search").oninput=e=>list(k,e.target.value)}
function cell(k,v){if(["salary","amount","total_fee","paid_amount","due_amount","monthly_fee"].includes(k))return money(v);if(["status","admission_status","verified"].includes(k))return `<span class="badge ${["Active","Present","Admitted","Yes","Available","Returned"].includes(v)?"green":["Absent","Inactive","Cancelled","Lost"].includes(v)?"red":"amber"}">${esc(v)}</span>`;return esc(v)}
function table(k,rows){let m=modules[k];return `<div class="table-wrap"><table><thead><tr>${m.cols.map(c=>`<th>${c[1]}</th>`).join("")}${canEdit(k)?'<th class="actions-col">Actions</th>':""}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${m.cols.map(c=>`<td>${cell(c[0],r[c[0]])}</td>`).join("")}${canEdit(k)?`<td class="actions-col"><button class="edit" onclick='openEdit("${k}",${JSON.stringify(r).replace(/'/g,"&#39;")})'>Edit</button> <button class="danger" onclick='removeRow("${k}","${r.id}")'>Delete</button></td>`:""}</tr>`).join(""):`<tr><td class="muted" colspan="${m.cols.length+1}">No records found</td></tr>`}</tbody></table></div>`}
function normalize(k,o){["total_fee","discount","paid_amount","salary","max_marks","marks_obtained","monthly_fee","amount","period_no"].forEach(x=>{if(x in o)o[x]=Number(o[x]||0)});if(k==="fees")o.due_amount=Math.max(0,Number(o.total_fee||0)-Number(o.discount||0)-Number(o.paid_amount||0));if(k==="exams")o.percentage=Number(o.max_marks)?+(Number(o.marks_obtained)*100/Number(o.max_marks)).toFixed(2):0}
function openAdd(k){if(!canEdit(k)||!modules[k])return;let m=modules[k];$("modalTitle").textContent="+ Add New "+m.title;$("form").innerHTML=m.fields.map(f=>fieldHTML(f,(f[2]==="date"&&["date","admission_date"].includes(f[0]))?{[f[0]]:today()}:{})).join("")+`<div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div>`;$("modal").classList.remove("hidden");$("form").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));normalize(k,o);let {error}=await sb.from(m.table).insert(o);if(error)return toast(error.message);toast("Saved successfully");closeModal();render(k)}}
function openEdit(k,row){if(!canEdit(k))return;let m=modules[k];$("modalTitle").textContent="Edit "+m.title;$("form").innerHTML=m.fields.map(f=>fieldHTML(f,row)).join("")+`<div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Update</button></div>`;$("modal").classList.remove("hidden");$("form").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));normalize(k,o);let {error}=await sb.from(m.table).update(o).eq("id",row.id);if(error)return toast(error.message);toast("Updated");closeModal();render(k)}}
function closeModal(){$("modal").classList.add("hidden");$("form").innerHTML=""}
async function removeRow(k,id){if(!canEdit(k)||!confirm("Delete this record?"))return;let {error}=await sb.from(modules[k].table).delete().eq("id",id);if(error)return toast(error.message);toast("Deleted");render(k)}
async function balance(){page="balance";setHead("Balance Sheet","Live financial position",false);let[f,i,e]=await Promise.all([sum("fees","paid_amount"),sum("income","amount"),sum("expenses","amount")]),net=f+i-e;$("content").innerHTML=`<div class="cards">${stat("Fees",money(f),"Collected")}${stat("Other Income",money(i),"Receipts")}${stat("Expenses",money(e),"Payments")}${stat("Closing Balance",money(net),"Current net")}</div><div class="panel"><div class="panel-head"><h3>Financial Summary</h3><button class="secondary" onclick="window.print()">Print</button></div><table><tbody><tr><td>Fee Collection</td><td>${money(f)}</td></tr><tr><td>Other Income</td><td>${money(i)}</td></tr><tr><td>Total Receipts</td><td>${money(f+i)}</td></tr><tr><td>Total Expenses</td><td>${money(e)}</td></tr><tr><td><b>Closing Balance</b></td><td class="${net>=0?"positive":"negative"}"><b>${money(net)}</b></td></tr></tbody></table></div>`}
async function users(){page="users";setHead("Users & Roles","Assign login permission",false);let{data,error}=await sb.from("profiles").select("*").order("created_at",{ascending:true});if(error)return $("content").innerHTML=`<div class="panel">${esc(error.message)}</div>`;let roles=["super_admin","admin","principal","admission","accountant","teacher","librarian","transport","student","parent","viewer"];$("content").innerHTML=`<div class="panel"><div class="panel-head"><h3>User Accounts</h3></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Save</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td><select id="role_${x.id}">${roles.map(r=>`<option ${r===x.role?"selected":""} value="${r}">${r}</option>`).join("")}</select></td><td><select id="status_${x.id}"><option ${x.status==="active"?"selected":""}>active</option><option ${x.status==="disabled"?"selected":""}>disabled</option></select></td><td><button class="primary" onclick="saveRole('${x.id}')">Save</button></td></tr>`).join("")}</tbody></table></div></div>`}
async function saveRole(id){let role=$("role_"+id).value,status=$("status_"+id).value;let{error}=await sb.from("profiles").update({role,status}).eq("id",id);if(error)return toast(error.message);toast("Permission updated")}
function reports(){page="reports";setHead("Reports","Print and backup",false);$("content").innerHTML=`<div class="panel"><div class="panel-head"><h3>Management Reports</h3><div class="toolbar"><button class="secondary" onclick="window.print()">Print Current</button><button class="primary" onclick="backup()">Export Cloud Backup</button></div></div><p class="muted">Dashboard, financial summary और module lists को print किया जा सकता है। Backup JSON में सभी main tables export होती हैं।</p></div>`}
async function backup(){let ts=Object.keys(modules).map(k=>modules[k].table),out={school:"L D MODERN EDUCATION ACADEMY",exported_at:new Date().toISOString(),data:{}};for(let t of [...new Set(ts)]){let{data}=await sb.from(t).select("*");out.data[t]=data||[]}let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:"application/json"}));a.download="LD-Modern-Ultimate-ERP-Backup.json";a.click();URL.revokeObjectURL(a.href)}
function settings(){page="settings";setHead("Settings","School & cloud settings",false);$("content").innerHTML=`<div class="panel"><h3>L D MODERN EDUCATION ACADEMY</h3><p class="muted">Nursery to Class 10 • Cloud ERP</p></div><div class="panel"><h3>Cloud Database</h3><p><span class="badge green">Connected</span></p><p class="muted">${esc(cfg.url)}</p><button class="danger" onclick="localStorage.removeItem(CKEY);location.reload()">Change Cloud Connection</button></div><div class="panel"><h3>Logged in</h3><p>${esc(user.email)}</p><p>Role: <b>${esc(profile.role)}</b></p></div>`}
async function render(p){if(!can(p)){toast("Permission denied");return}page=p;if(modules[p])return list(p);if(p==="dashboard")return dashboard();if(p==="balance")return balance();if(p==="users")return users();if(p==="reports")return reports();if(p==="settings")return settings()}
boot();